version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=Le_Shtroumpf
      - POSTGRES_PASSWORD=1234azerty56789
      - POSTGRES_DB=shtroumpfette
    ports:
      - '5432:5432'
    volumes:
      - .db_run:/run
  bot:
    image: schtroumpfette
    restart: always
    volumes:
      - .bot_run:/run